const fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1200,height:950}});
 await page.route('https://pafford.imagetrendelite.com/**',r=>r.fulfill({body:'<html><body><div id="panel-header">Transport Info</div><div id="form-composer"><input id="25089"></div></body></html>',contentType:'text/html'}));
 await page.goto('https://pafford.imagetrendelite.com/#/Incident123/Form42');
 const artwork='data:image/png;base64,'+fs.readFileSync('assets/clear-warning.png').toString('base64');
 await page.evaluate(art=>window.GM_getResourceURL=()=>art,artwork);
 await page.addScriptTag({content:fs.readFileSync('src/imagetrend-a15-helper.user.js','utf8')});
 const helper=page.locator('#it-a15-helper-host');
 await helper.locator('#launch').click();
 assert.equal(await helper.locator('#scan').getAttribute('data-state'),'pending');
 assert.equal(await helper.getByText('Add four routine procedures',{exact:true}).count(),0);
 await helper.locator('#scan').click();
 await page.waitForFunction(()=>document.querySelector('#it-a15-helper-host').shadowRoot.querySelector('#scan').dataset.state==='ready');
 assert.equal(await helper.locator('#timeline').getAttribute('data-state'),'error');
 await helper.locator('#ack').check();
 assert.equal(await helper.locator('#run').isEnabled(),true);
 await helper.locator('#run').click();
 await page.waitForFunction(()=>document.getElementById('25089').value==='1');
 await helper.getByRole('tab',{name:'Clear',exact:true}).click();
 assert.equal(await helper.locator('#clearvalues').isEnabled(),true);
 let warnings=0;
 page.on('dialog',async d=>{warnings++;await d.accept();});
 await helper.locator('#clearvalues').click();
 assert.equal(warnings,1);
 assert.equal(await page.locator('[id="25089"]').inputValue(),'1');
 assert.equal(await helper.locator('#confirm').isVisible(),true);
 await page.screenshot({path:'../../cumulative-clear-preview.png'});
 await helper.locator('#cancelclear').click();
 assert.equal(await page.locator('[id="25089"]').inputValue(),'1');
 await helper.locator('#clearvalues').click();
 await helper.locator('#yesclear').click();
 await page.waitForFunction(()=>document.getElementById('25089').value==='');
 assert.equal(warnings,2);
 await page.evaluate(()=>document.getElementById('panel-header').textContent='Procedures & Medications');
 await page.waitForFunction(()=>document.querySelector('#it-a15-helper-host').shadowRoot.querySelector('nav button[aria-selected="true"]').textContent==='Treatment');
 await page.screenshot({path:'../../cumulative-panel-preview.png'});
 console.log('PASS GUI status, acknowledgment, section sync, scoped clear, two warnings and cancel');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
